# This file was generated by GoReleaser. DO NOT EDIT.
cask "certkit" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  name "certkit"
  desc "A certificate management tool that ingests TLS/SSL certificates and keys, catalogs them in SQLite, and exports organized bundles."
  homepage "https://github.com/sensiblebit/certkit"
  version "0.7.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certkit"

  on_macos do
    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_darwin_amd64.tar.gz"
      sha256 "260aba40616d5467491356ba58918603833793999277f142c78a17ad3979dabc"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_darwin_arm64.tar.gz"
      sha256 "ec90bc293e99859387093d19fb0606a53816ff6b4ae50aa35da8083d0fb1c86a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_linux_amd64.tar.gz"
      sha256 "650467f39936532cf83bffec1b555f331df26c8494cea230433041c343a9c44e"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_linux_arm64.tar.gz"
      sha256 "3f4ed6de4370b51b41f2e9c12735de78585881759136abad61a1399f3003e88a"
    end
  end

  # No zap stanza required
end
