# This file was generated by GoReleaser. DO NOT EDIT.
cask "certkit" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  name "certkit"
  desc "A certificate management tool that ingests TLS/SSL certificates and keys, catalogs them in SQLite, and exports organized bundles."
  homepage "https://github.com/sensiblebit/certkit"
  version "0.6.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certkit"

  on_macos do
    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_darwin_amd64.tar.gz"
      sha256 "6e791f8bd11267e7eeafaad2a7b373fca92b0217ec3891576525e1483586bb5a"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_darwin_arm64.tar.gz"
      sha256 "03ac0522b3f426169a0b583d84d28356ceee8fa7be2f89254aee0ca25dcad582"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_linux_amd64.tar.gz"
      sha256 "5c75be13681ab54dd897b54a22f32018ec179a7de5f7941e0bcca4de560475cd"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_linux_arm64.tar.gz"
      sha256 "8db1ffa33abfb42a2ae3d3a7d7f3689eba851305076686a8d505e74d72cb894e"
    end
  end

  # No zap stanza required
end
