# This file is auto-generated by certkit nightly workflow. DO NOT EDIT.
cask "certkit@nightly" do
  name "certkit nightly"
  desc "Nightly snapshots of certkit certificate tooling"
  homepage "https://github.com/sensiblebit/certkit"
  version "nightly-20260311042940-6ddcfe4"

  livecheck do
    skip "Updated on every push to main."
  end

  conflicts_with cask: "certkit"

  binary "certkit"

  on_macos do
    postflight do
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end

    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_darwin_amd64.tar.gz"
      sha256 "a578911491eb4ee4fea82cc71db5dff8d44105f1ad575064c4ac4c273d695c10"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_darwin_arm64.tar.gz"
      sha256 "cee2524ac94203dafcc47cb99964aa01c469ebc998189b488b733e0393dbf7fa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_linux_amd64.tar.gz"
      sha256 "b7d299ba1d2694e0e2bdd8da4edcfd78dbf20459b303d991cd6163e3be7cde00"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_linux_arm64.tar.gz"
      sha256 "3986cfd8125dfd31d6a292a8424df2a95cbf4b1975c22d55703d5a41ce8d1ce4"
    end
  end
end
