# This file was generated by GoReleaser. DO NOT EDIT.
cask "certwrangler" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  name "certwrangler"
  desc "A certificate management tool that ingests TLS/SSL certificates and keys, catalogs them in SQLite, and exports organized bundles."
  homepage "https://github.com/sensiblebit/certWrangler"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certwrangler"

  on_macos do
    on_intel do
      url "https://github.com/sensiblebit/certWrangler/releases/download/v#{version}/certWrangler_#{version}_darwin_amd64.tar.gz"
      sha256 "a54e59fef6ef2780c199e71815ab7b410b1181605480474d56a7831ae130e60d"
    end
    on_arm do
      url "https://github.com/sensiblebit/certWrangler/releases/download/v#{version}/certWrangler_#{version}_darwin_arm64.tar.gz"
      sha256 "946beb2c27531ed7b33e20a2370375d75e3cce159c425e2cffc364f23b4e9148"
    end
  end

  # No zap stanza required
end
