# This file is auto-generated by certkit nightly workflow. DO NOT EDIT.
cask "certkit@nightly" do
  name "certkit nightly"
  desc "Nightly snapshots of certkit certificate tooling"
  homepage "https://github.com/sensiblebit/certkit"
  version "nightly-20260310144903-f37a891"

  livecheck do
    skip "Updated on every push to main."
  end

  conflicts_with cask: "certkit"

  binary "certkit"

  on_macos do
    postflight do
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end

    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_darwin_amd64.tar.gz"
      sha256 "9d99d5024861b14f07b7bf38b4912712c86eb51935d50d8beb06ec3dce874ba5"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_darwin_arm64.tar.gz"
      sha256 "64de86c16d733135d49dfce49c7a20445ac8ee8e1ee0828a625fad0f045b13aa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_linux_amd64.tar.gz"
      sha256 "ecd202029c0790bf6222621db6cebfbcae5a0539f2f0b74fb42a54e0e16eeb7d"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_linux_arm64.tar.gz"
      sha256 "cd468e813d699ff1878a69ddbb71b1c71c163ca67c62bb701892b68f1ae6de2f"
    end
  end
end
