# This file was generated by GoReleaser. DO NOT EDIT.
cask "certwrangler" do
  name "certwrangler"
  desc "A certificate management tool that ingests TLS/SSL certificates and keys, catalogs them in SQLite, and exports organized bundles."
  homepage "https://github.com/sensiblebit/certWrangler"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certwrangler"

  on_macos do
    on_intel do
      url "https://github.com/sensiblebit/certWrangler/releases/download/v#{version}/certWrangler_#{version}_darwin_amd64.tar.gz"
      sha256 "30fc275e12dec4c9fc3efcaf56999358fdd559d1788acc042e30649a43bb20d3"
    end
    on_arm do
      url "https://github.com/sensiblebit/certWrangler/releases/download/v#{version}/certWrangler_#{version}_darwin_arm64.tar.gz"
      sha256 "fd84f7e3223a113ae51c1e7ef0da25e0d41379bdf6984b331dd6c823a5051e23"
    end
  end

  # No zap stanza required
end
