# This file is auto-generated by certkit nightly workflow. DO NOT EDIT.
cask "certkit@nightly" do
  name "certkit nightly"
  desc "Nightly snapshots of certkit certificate tooling"
  homepage "https://github.com/sensiblebit/certkit"
  version "nightly-20260309224324-cee87c1"

  livecheck do
    skip "Updated on every push to main."
  end

  conflicts_with cask: "certkit"

  binary "certkit"

  on_macos do
    postflight do
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end

    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_darwin_amd64.tar.gz"
      sha256 "cbba00e75dbacedaaad79314d90f6927d36d6852b97929df7228f58b3277af47"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_darwin_arm64.tar.gz"
      sha256 "ffcb7c6fdda83eb4f474b61dd788cb2777ef9aba81b71a71dff1a4847a8e1d49"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_linux_amd64.tar.gz"
      sha256 "2ac36523c32f7a28b0f3beaceb3a629f3f5999bdc741003744558d383d8e358b"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/nightly/certkit_#{version}_linux_arm64.tar.gz"
      sha256 "b2f55be35a880f8108e78eaf461c6587a2660521f168103561c570c3e3874281"
    end
  end
end
