# This file was generated by GoReleaser. DO NOT EDIT.
cask "certwrangler" do
  no_quarantine true

  name "certwrangler"
  desc "A certificate management tool that ingests TLS/SSL certificates and keys, catalogs them in SQLite, and exports organized bundles."
  homepage "https://github.com/sensiblebit/certWrangler"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certwrangler"

  on_macos do
    on_intel do
      url "https://github.com/sensiblebit/certWrangler/releases/download/v#{version}/certWrangler_#{version}_darwin_amd64.tar.gz"
      sha256 "ef8366de2855f2f55a8b952f1e797ee86cb110ab6f4c7eb28dc3b7d5a52018fe"
    end
    on_arm do
      url "https://github.com/sensiblebit/certWrangler/releases/download/v#{version}/certWrangler_#{version}_darwin_arm64.tar.gz"
      sha256 "6d3abd17e1a24ed1df8167bf3bd2c5bd73217f8ee5e5d02ff771acba555f42d3"
    end
  end

  # No zap stanza required
end
