# This file was generated by GoReleaser. DO NOT EDIT.
cask "certkit" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  name "certkit"
  desc "A certificate management tool that ingests TLS/SSL certificates and keys, catalogs them in SQLite, and exports organized bundles."
  homepage "https://github.com/sensiblebit/certkit"
  version "0.7.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certkit"

  on_macos do
    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_darwin_amd64.tar.gz"
      sha256 "78b2468a6c99bd9f2ec63ac9afc1cae3eed0245b34fbfaf5d2c9b3ccaac5b212"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_darwin_arm64.tar.gz"
      sha256 "2a8d75fba35cb2c9bf34fdbac7dd511d96cb24f73e11ba7719e80c7a14a36cde"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_linux_amd64.tar.gz"
      sha256 "007e6c0d65c3ce406901162eb501ca5fb026388060a0f25b6c18c51d11361f95"
    end
    on_arm do
      url "https://github.com/sensiblebit/certkit/releases/download/v#{version}/certkit_#{version}_linux_arm64.tar.gz"
      sha256 "9e615486120cb8b6822e0d90b128c3ed25f1553e09067b000f8f04d0ecc8e07d"
    end
  end

  # No zap stanza required
end
