# This file was generated by GoReleaser. DO NOT EDIT.
cask "vanityssh" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  name "vanityssh"
  desc "Generate ED25519 SSH keys with vanity public keys"
  homepage "https://github.com/danielewood/vanityssh-go"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vanityssh"

  on_macos do
    on_intel do
      url "https://github.com/danielewood/vanityssh-go/releases/download/v#{version}/vanityssh-go_#{version}_darwin_amd64.tar.gz"
      sha256 "554db4c585e0159382279e1e9861281f7e8d76093ca62676f3cf01c5e2ee3aef"
    end
    on_arm do
      url "https://github.com/danielewood/vanityssh-go/releases/download/v#{version}/vanityssh-go_#{version}_darwin_arm64.tar.gz"
      sha256 "3ea75b25522b690e4e3f5746264e53bd4b507164f54f72da52b6ee1f8651c5a6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielewood/vanityssh-go/releases/download/v#{version}/vanityssh-go_#{version}_linux_amd64.tar.gz"
      sha256 "f1696d7d4e02748b9a99c5e3c39df18532458ccf1ea5a3d0345daee6d6c102bc"
    end
    on_arm do
      url "https://github.com/danielewood/vanityssh-go/releases/download/v#{version}/vanityssh-go_#{version}_linux_arm64.tar.gz"
      sha256 "09a3f63d83204e9cc483abe46891f61e5073b94b12bbcc92ab9fe084bc76b4e2"
    end
  end

  # No zap stanza required
end
