# This file was generated by GoReleaser. DO NOT EDIT.
cask "vanityssh" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  name "vanityssh"
  desc "Generate ED25519 SSH keys with vanity public keys"
  homepage "https://github.com/danielewood/vanityssh-go"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vanityssh"

  on_macos do
    on_intel do
      url "https://github.com/danielewood/vanityssh-go/releases/download/v#{version}/vanityssh-go_#{version}_darwin_amd64.tar.gz"
      sha256 "5af5bf49a2478a5e0ac6da89ea41434da3886958cfee0886291c2f5c93626e28"
    end
    on_arm do
      url "https://github.com/danielewood/vanityssh-go/releases/download/v#{version}/vanityssh-go_#{version}_darwin_arm64.tar.gz"
      sha256 "18cc068fac5e74c40f5b999e163946b0584633eccf69034ac51cfcf09d8b2c96"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielewood/vanityssh-go/releases/download/v#{version}/vanityssh-go_#{version}_linux_amd64.tar.gz"
      sha256 "70ee3658af673f9353607f02884814b66750bdbb7b29fd05d100036f4e3dee27"
    end
    on_arm do
      url "https://github.com/danielewood/vanityssh-go/releases/download/v#{version}/vanityssh-go_#{version}_linux_arm64.tar.gz"
      sha256 "a6d1c022ce2feceb26c5993b4421dfcbbf9451348fa8a7bcf126898fe42fc264"
    end
  end

  # No zap stanza required
end
